'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq

Partial Public Class COOPInventaire_TP3_testsEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=COOPInventaire_TP3_testsEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property Tb_Categorie() As DbSet(Of Tb_Categorie)
    Public Property Tb_Commande() As DbSet(Of Tb_Commande)
    Public Property Tb_CommandeItem() As DbSet(Of Tb_CommandeItem)
    Public Property Tb_Departement() As DbSet(Of Tb_Departement)
    Public Property Tb_Emplacement() As DbSet(Of Tb_Emplacement)
    Public Property Tb_Facture() As DbSet(Of Tb_Facture)
    Public Property Tb_FactureItem() As DbSet(Of Tb_FactureItem)
    Public Property Tb_Fournisseur() As DbSet(Of Tb_Fournisseur)
    Public Property Tb_Inventaire() As DbSet(Of Tb_Inventaire)
    Public Property Tb_Membre() As DbSet(Of Tb_Membre)
    Public Property Tb_NiveauAcces() As DbSet(Of Tb_NiveauAcces)
    Public Property Tb_Produit() As DbSet(Of Tb_Produit)
    Public Property Tb_Taxe() As DbSet(Of Tb_Taxe)
    Public Property Tb_Utilisateur() As DbSet(Of Tb_Utilisateur)
    Public Property Tb_Localisation() As DbSet(Of Tb_Localisation)

    Public Overridable Function DeleteCategorie(original_ID As Nullable(Of Integer), isNull_Nom As Nullable(Of Integer), original_Nom As String) As Integer
        Dim original_IDParameter As ObjectParameter = If(original_ID.HasValue, New ObjectParameter("Original_ID", original_ID), New ObjectParameter("Original_ID", GetType(Integer)))

        Dim isNull_NomParameter As ObjectParameter = If(isNull_Nom.HasValue, New ObjectParameter("IsNull_Nom", isNull_Nom), New ObjectParameter("IsNull_Nom", GetType(Integer)))

        Dim original_NomParameter As ObjectParameter = If(original_Nom IsNot Nothing, New ObjectParameter("Original_Nom", original_Nom), New ObjectParameter("Original_Nom", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("DeleteCategorie", original_IDParameter, isNull_NomParameter, original_NomParameter)
    End Function

    Public Overridable Function DeleteDepartement(original_ID As Nullable(Of Integer), isNull_Code As Nullable(Of Integer), original_Code As String) As Integer
        Dim original_IDParameter As ObjectParameter = If(original_ID.HasValue, New ObjectParameter("Original_ID", original_ID), New ObjectParameter("Original_ID", GetType(Integer)))

        Dim isNull_CodeParameter As ObjectParameter = If(isNull_Code.HasValue, New ObjectParameter("IsNull_Code", isNull_Code), New ObjectParameter("IsNull_Code", GetType(Integer)))

        Dim original_CodeParameter As ObjectParameter = If(original_Code IsNot Nothing, New ObjectParameter("Original_Code", original_Code), New ObjectParameter("Original_Code", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("DeleteDepartement", original_IDParameter, isNull_CodeParameter, original_CodeParameter)
    End Function

    Public Overridable Function DeleteInventaireComplet(iD As Nullable(Of Integer)) As Integer
        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("DeleteInventaireComplet", iDParameter)
    End Function

    Public Overridable Function InsertCategorie(nom As String) As ObjectResult(Of InsertCategorie_Result)
        Dim nomParameter As ObjectParameter = If(nom IsNot Nothing, New ObjectParameter("Nom", nom), New ObjectParameter("Nom", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of InsertCategorie_Result)("InsertCategorie", nomParameter)
    End Function

    Public Overridable Function InsertDepartement(code As String) As ObjectResult(Of InsertDepartement_Result)
        Dim codeParameter As ObjectParameter = If(code IsNot Nothing, New ObjectParameter("Code", code), New ObjectParameter("Code", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of InsertDepartement_Result)("InsertDepartement", codeParameter)
    End Function

    Public Overridable Function InsertInventaireComplet(codeProduit As String, description As String, emplacement As String, categorie As String, departement As String, fournisseurCode As String, fournisseurNom As String, prixVente As Nullable(Of Double), qt As Nullable(Of Integer)) As Integer
        Dim codeProduitParameter As ObjectParameter = If(codeProduit IsNot Nothing, New ObjectParameter("CodeProduit", codeProduit), New ObjectParameter("CodeProduit", GetType(String)))

        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Dim emplacementParameter As ObjectParameter = If(emplacement IsNot Nothing, New ObjectParameter("Emplacement", emplacement), New ObjectParameter("Emplacement", GetType(String)))

        Dim categorieParameter As ObjectParameter = If(categorie IsNot Nothing, New ObjectParameter("Categorie", categorie), New ObjectParameter("Categorie", GetType(String)))

        Dim departementParameter As ObjectParameter = If(departement IsNot Nothing, New ObjectParameter("Departement", departement), New ObjectParameter("Departement", GetType(String)))

        Dim fournisseurCodeParameter As ObjectParameter = If(fournisseurCode IsNot Nothing, New ObjectParameter("FournisseurCode", fournisseurCode), New ObjectParameter("FournisseurCode", GetType(String)))

        Dim fournisseurNomParameter As ObjectParameter = If(fournisseurNom IsNot Nothing, New ObjectParameter("FournisseurNom", fournisseurNom), New ObjectParameter("FournisseurNom", GetType(String)))

        Dim prixVenteParameter As ObjectParameter = If(prixVente.HasValue, New ObjectParameter("PrixVente", prixVente), New ObjectParameter("PrixVente", GetType(Double)))

        Dim qtParameter As ObjectParameter = If(qt.HasValue, New ObjectParameter("Qt", qt), New ObjectParameter("Qt", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("InsertInventaireComplet", codeProduitParameter, descriptionParameter, emplacementParameter, categorieParameter, departementParameter, fournisseurCodeParameter, fournisseurNomParameter, prixVenteParameter, qtParameter)
    End Function

    Public Overridable Function ReduireQtInventaireComplet(iD As Nullable(Of Integer), amount As Nullable(Of Integer)) As Integer
        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Integer)))

        Dim amountParameter As ObjectParameter = If(amount.HasValue, New ObjectParameter("Amount", amount), New ObjectParameter("Amount", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("ReduireQtInventaireComplet", iDParameter, amountParameter)
    End Function

    Public Overridable Function SelectCategorie() As ObjectResult(Of SelectCategorie_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectCategorie_Result)("SelectCategorie")
    End Function

    Public Overridable Function SelectDepartement() As ObjectResult(Of SelectDepartement_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectDepartement_Result)("SelectDepartement")
    End Function

    Public Overridable Function SelectInventaireComplet() As ObjectResult(Of SelectInventaireComplet_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireComplet_Result)("SelectInventaireComplet")
    End Function

    Public Overridable Function SelectInventaireCompletFiltreCodeProduit(codeProduit As String) As ObjectResult(Of SelectInventaireCompletFiltreCodeProduit_Result)
        Dim codeProduitParameter As ObjectParameter = If(codeProduit IsNot Nothing, New ObjectParameter("CodeProduit", codeProduit), New ObjectParameter("CodeProduit", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletFiltreCodeProduit_Result)("SelectInventaireCompletFiltreCodeProduit", codeProduitParameter)
    End Function

    Public Overridable Function SelectInventaireCompletFiltreDescription(description As String) As ObjectResult(Of SelectInventaireCompletFiltreDescription_Result)
        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletFiltreDescription_Result)("SelectInventaireCompletFiltreDescription", descriptionParameter)
    End Function

    Public Overridable Function SelectInventaireCompletParCategorie(categorieID As Nullable(Of Integer)) As ObjectResult(Of SelectInventaireCompletParCategorie_Result)
        Dim categorieIDParameter As ObjectParameter = If(categorieID.HasValue, New ObjectParameter("CategorieID", categorieID), New ObjectParameter("CategorieID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletParCategorie_Result)("SelectInventaireCompletParCategorie", categorieIDParameter)
    End Function

    Public Overridable Function SelectInventaireCompletParCategorieFiltreCodeProduit(categorieID As Nullable(Of Integer), codeProduit As String) As ObjectResult(Of SelectInventaireCompletParCategorieFiltreCodeProduit_Result)
        Dim categorieIDParameter As ObjectParameter = If(categorieID.HasValue, New ObjectParameter("CategorieID", categorieID), New ObjectParameter("CategorieID", GetType(Integer)))

        Dim codeProduitParameter As ObjectParameter = If(codeProduit IsNot Nothing, New ObjectParameter("CodeProduit", codeProduit), New ObjectParameter("CodeProduit", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletParCategorieFiltreCodeProduit_Result)("SelectInventaireCompletParCategorieFiltreCodeProduit", categorieIDParameter, codeProduitParameter)
    End Function

    Public Overridable Function SelectInventaireCompletParCategorieFiltreDescription(categorieID As Nullable(Of Integer), description As String) As ObjectResult(Of SelectInventaireCompletParCategorieFiltreDescription_Result)
        Dim categorieIDParameter As ObjectParameter = If(categorieID.HasValue, New ObjectParameter("CategorieID", categorieID), New ObjectParameter("CategorieID", GetType(Integer)))

        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletParCategorieFiltreDescription_Result)("SelectInventaireCompletParCategorieFiltreDescription", categorieIDParameter, descriptionParameter)
    End Function

    Public Overridable Function SelectInventaireCompletParDepartement(departementID As Nullable(Of Integer)) As ObjectResult(Of SelectInventaireCompletParDepartement_Result)
        Dim departementIDParameter As ObjectParameter = If(departementID.HasValue, New ObjectParameter("DepartementID", departementID), New ObjectParameter("DepartementID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletParDepartement_Result)("SelectInventaireCompletParDepartement", departementIDParameter)
    End Function

    Public Overridable Function SelectInventaireCompletParDepartementFiltreCodeProduit(departementID As Nullable(Of Integer), codeProduit As String) As ObjectResult(Of SelectInventaireCompletParDepartementFiltreCodeProduit_Result)
        Dim departementIDParameter As ObjectParameter = If(departementID.HasValue, New ObjectParameter("DepartementID", departementID), New ObjectParameter("DepartementID", GetType(Integer)))

        Dim codeProduitParameter As ObjectParameter = If(codeProduit IsNot Nothing, New ObjectParameter("CodeProduit", codeProduit), New ObjectParameter("CodeProduit", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletParDepartementFiltreCodeProduit_Result)("SelectInventaireCompletParDepartementFiltreCodeProduit", departementIDParameter, codeProduitParameter)
    End Function

    Public Overridable Function SelectInventaireCompletParDepartementFiltreDescription(departementID As Nullable(Of Integer), description As String) As ObjectResult(Of SelectInventaireCompletParDepartementFiltreDescription_Result)
        Dim departementIDParameter As ObjectParameter = If(departementID.HasValue, New ObjectParameter("DepartementID", departementID), New ObjectParameter("DepartementID", GetType(Integer)))

        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireCompletParDepartementFiltreDescription_Result)("SelectInventaireCompletParDepartementFiltreDescription", departementIDParameter, descriptionParameter)
    End Function

    Public Overridable Function SelectInventaireReduitFacture() As ObjectResult(Of SelectInventaireReduitFacture_Result)
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireReduitFacture_Result)("SelectInventaireReduitFacture")
    End Function

    Public Overridable Function SelectInventaireReduitFactureFiltreCodeProduit(codeProduit As String) As ObjectResult(Of SelectInventaireReduitFactureFiltreCodeProduit_Result)
        Dim codeProduitParameter As ObjectParameter = If(codeProduit IsNot Nothing, New ObjectParameter("CodeProduit", codeProduit), New ObjectParameter("CodeProduit", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireReduitFactureFiltreCodeProduit_Result)("SelectInventaireReduitFactureFiltreCodeProduit", codeProduitParameter)
    End Function

    Public Overridable Function SelectInventaireReduitFactureFiltreDescription(description As String) As ObjectResult(Of SelectInventaireReduitFactureFiltreDescription_Result)
        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of SelectInventaireReduitFactureFiltreDescription_Result)("SelectInventaireReduitFactureFiltreDescription", descriptionParameter)
    End Function

    Public Overridable Function sp_alterdiagram(diagramname As String, owner_id As Nullable(Of Integer), version As Nullable(Of Integer), definition As Byte()) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Dim versionParameter As ObjectParameter = If(version.HasValue, New ObjectParameter("version", version), New ObjectParameter("version", GetType(Integer)))

        Dim definitionParameter As ObjectParameter = If(definition IsNot Nothing, New ObjectParameter("definition", definition), New ObjectParameter("definition", GetType(Byte())))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter)
    End Function

    Public Overridable Function sp_creatediagram(diagramname As String, owner_id As Nullable(Of Integer), version As Nullable(Of Integer), definition As Byte()) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Dim versionParameter As ObjectParameter = If(version.HasValue, New ObjectParameter("version", version), New ObjectParameter("version", GetType(Integer)))

        Dim definitionParameter As ObjectParameter = If(definition IsNot Nothing, New ObjectParameter("definition", definition), New ObjectParameter("definition", GetType(Byte())))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter)
    End Function

    Public Overridable Function sp_dropdiagram(diagramname As String, owner_id As Nullable(Of Integer)) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter)
    End Function

    Public Overridable Function sp_helpdiagramdefinition(diagramname As String, owner_id As Nullable(Of Integer)) As ObjectResult(Of sp_helpdiagramdefinition_Result)
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_helpdiagramdefinition_Result)("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter)
    End Function

    Public Overridable Function sp_helpdiagrams(diagramname As String, owner_id As Nullable(Of Integer)) As ObjectResult(Of sp_helpdiagrams_Result)
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_helpdiagrams_Result)("sp_helpdiagrams", diagramnameParameter, owner_idParameter)
    End Function

    Public Overridable Function sp_renamediagram(diagramname As String, owner_id As Nullable(Of Integer), new_diagramname As String) As Integer
        Dim diagramnameParameter As ObjectParameter = If(diagramname IsNot Nothing, New ObjectParameter("diagramname", diagramname), New ObjectParameter("diagramname", GetType(String)))

        Dim owner_idParameter As ObjectParameter = If(owner_id.HasValue, New ObjectParameter("owner_id", owner_id), New ObjectParameter("owner_id", GetType(Integer)))

        Dim new_diagramnameParameter As ObjectParameter = If(new_diagramname IsNot Nothing, New ObjectParameter("new_diagramname", new_diagramname), New ObjectParameter("new_diagramname", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter)
    End Function

    Public Overridable Function sp_upgraddiagrams() As Integer
        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("sp_upgraddiagrams")
    End Function

    Public Overridable Function UpdateCategorie(nom As String, original_ID As Nullable(Of Integer), isNull_Nom As Nullable(Of Integer), original_Nom As String, iD As Nullable(Of Integer)) As ObjectResult(Of UpdateCategorie_Result)
        Dim nomParameter As ObjectParameter = If(nom IsNot Nothing, New ObjectParameter("Nom", nom), New ObjectParameter("Nom", GetType(String)))

        Dim original_IDParameter As ObjectParameter = If(original_ID.HasValue, New ObjectParameter("Original_ID", original_ID), New ObjectParameter("Original_ID", GetType(Integer)))

        Dim isNull_NomParameter As ObjectParameter = If(isNull_Nom.HasValue, New ObjectParameter("IsNull_Nom", isNull_Nom), New ObjectParameter("IsNull_Nom", GetType(Integer)))

        Dim original_NomParameter As ObjectParameter = If(original_Nom IsNot Nothing, New ObjectParameter("Original_Nom", original_Nom), New ObjectParameter("Original_Nom", GetType(String)))

        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of UpdateCategorie_Result)("UpdateCategorie", nomParameter, original_IDParameter, isNull_NomParameter, original_NomParameter, iDParameter)
    End Function

    Public Overridable Function UpdateDepartement(code As String, original_ID As Nullable(Of Integer), isNull_Code As Nullable(Of Integer), original_Code As String, iD As Nullable(Of Integer)) As ObjectResult(Of UpdateDepartement_Result)
        Dim codeParameter As ObjectParameter = If(code IsNot Nothing, New ObjectParameter("Code", code), New ObjectParameter("Code", GetType(String)))

        Dim original_IDParameter As ObjectParameter = If(original_ID.HasValue, New ObjectParameter("Original_ID", original_ID), New ObjectParameter("Original_ID", GetType(Integer)))

        Dim isNull_CodeParameter As ObjectParameter = If(isNull_Code.HasValue, New ObjectParameter("IsNull_Code", isNull_Code), New ObjectParameter("IsNull_Code", GetType(Integer)))

        Dim original_CodeParameter As ObjectParameter = If(original_Code IsNot Nothing, New ObjectParameter("Original_Code", original_Code), New ObjectParameter("Original_Code", GetType(String)))

        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of UpdateDepartement_Result)("UpdateDepartement", codeParameter, original_IDParameter, isNull_CodeParameter, original_CodeParameter, iDParameter)
    End Function

    Public Overridable Function UpdateInventaireComplet(iD As Nullable(Of Integer), codeProduit As String, description As String, emplacement As String, categorie As String, departement As String, fournisseurCode As String, fournisseurNom As String, prixVente As Nullable(Of Double), qt As Nullable(Of Integer)) As Integer
        Dim iDParameter As ObjectParameter = If(iD.HasValue, New ObjectParameter("ID", iD), New ObjectParameter("ID", GetType(Integer)))

        Dim codeProduitParameter As ObjectParameter = If(codeProduit IsNot Nothing, New ObjectParameter("CodeProduit", codeProduit), New ObjectParameter("CodeProduit", GetType(String)))

        Dim descriptionParameter As ObjectParameter = If(description IsNot Nothing, New ObjectParameter("Description", description), New ObjectParameter("Description", GetType(String)))

        Dim emplacementParameter As ObjectParameter = If(emplacement IsNot Nothing, New ObjectParameter("Emplacement", emplacement), New ObjectParameter("Emplacement", GetType(String)))

        Dim categorieParameter As ObjectParameter = If(categorie IsNot Nothing, New ObjectParameter("Categorie", categorie), New ObjectParameter("Categorie", GetType(String)))

        Dim departementParameter As ObjectParameter = If(departement IsNot Nothing, New ObjectParameter("Departement", departement), New ObjectParameter("Departement", GetType(String)))

        Dim fournisseurCodeParameter As ObjectParameter = If(fournisseurCode IsNot Nothing, New ObjectParameter("FournisseurCode", fournisseurCode), New ObjectParameter("FournisseurCode", GetType(String)))

        Dim fournisseurNomParameter As ObjectParameter = If(fournisseurNom IsNot Nothing, New ObjectParameter("FournisseurNom", fournisseurNom), New ObjectParameter("FournisseurNom", GetType(String)))

        Dim prixVenteParameter As ObjectParameter = If(prixVente.HasValue, New ObjectParameter("PrixVente", prixVente), New ObjectParameter("PrixVente", GetType(Double)))

        Dim qtParameter As ObjectParameter = If(qt.HasValue, New ObjectParameter("Qt", qt), New ObjectParameter("Qt", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("UpdateInventaireComplet", iDParameter, codeProduitParameter, descriptionParameter, emplacementParameter, categorieParameter, departementParameter, fournisseurCodeParameter, fournisseurNomParameter, prixVenteParameter, qtParameter)
    End Function

End Class
