'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_CommandeItem
    Public Property ID As Integer
    Public Property ProduitID As Nullable(Of Integer)
    Public Property Qt As Nullable(Of Integer)
    Public Property DateReception As Nullable(Of Date)
    Public Property R1 As String

    Public Overridable Property Tb_Commande As ICollection(Of Tb_Commande) = New HashSet(Of Tb_Commande)
    Public Overridable Property Tb_Produit As Tb_Produit

End Class
