'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Commande
    Public Property ID As Integer
    Public Property UtilisateurID As Nullable(Of Integer)
    Public Property FournisseurID As Nullable(Of Integer)
    Public Property CommandeItemID As Nullable(Of Integer)
    Public Property No As Nullable(Of Integer)
    Public Property PO As String
    Public Property [Date] As Nullable(Of Date)
    Public Property NomExpediteur As String
    Public Property NoTracking As String
    Public Property R1 As String
    Public Property R2 As String

    Public Overridable Property Tb_CommandeItem As Tb_CommandeItem
    Public Overridable Property Tb_Fournisseur As Tb_Fournisseur
    Public Overridable Property Tb_Utilisateur As Tb_Utilisateur

End Class
