'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Departement
    Public Property ID As Integer
    Public Property Code As String
    Public Property Nom As String
    Public Property R1 As String
    Public Property R2 As String

    Public Overridable Property Tb_Inventaire As ICollection(Of Tb_Inventaire) = New HashSet(Of Tb_Inventaire)

End Class
