'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Facture
    Public Property ID As Integer
    Public Property MembreID As Nullable(Of Integer)
    Public Property UtilisateurID As Nullable(Of Integer)
    Public Property FactureItemID As Nullable(Of Integer)
    Public Property No As Nullable(Of Integer)
    Public Property [Date] As Nullable(Of Date)
    Public Property ModePaiement As String
    Public Property R1 As String
    Public Property R2 As String

    Public Overridable Property Tb_FactureItem As Tb_FactureItem
    Public Overridable Property Tb_Membre As Tb_Membre
    Public Overridable Property Tb_Utilisateur As Tb_Utilisateur

End Class
