'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Fournisseur
    Public Property ID As Integer
    Public Property Code As String
    Public Property Nom As String
    Public Property Addresse As String
    Public Property Tel1 As String
    Public Property Tel2 As String
    Public Property Fax As String
    Public Property CodePostal As String
    Public Property NomContact As String
    Public Property MargeRegulier As Nullable(Of Double)
    Public Property MargeMembre As Nullable(Of Double)
    Public Property R1 As String
    Public Property R2 As String

    Public Overridable Property Tb_Commande As ICollection(Of Tb_Commande) = New HashSet(Of Tb_Commande)
    Public Overridable Property Tb_Inventaire As ICollection(Of Tb_Inventaire) = New HashSet(Of Tb_Inventaire)

End Class
