'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Inventaire
    Public Property ID As Integer
    Public Property ProduitID As Nullable(Of Integer)
    Public Property DepartementID As Nullable(Of Integer)
    Public Property CategorieID As Nullable(Of Integer)
    Public Property FournisseurID As Nullable(Of Integer)
    Public Property Qt As Nullable(Of Integer)
    Public Property PrixAchat As Nullable(Of Double)
    Public Property PrixVente As Nullable(Of Double)
    Public Property PrixVenteMembre As Nullable(Of Double)
    Public Property R1 As Nullable(Of Integer)
    Public Property R2 As String
    Public Property R3 As String

    Public Overridable Property Tb_Categorie As Tb_Categorie
    Public Overridable Property Tb_Departement As Tb_Departement
    Public Overridable Property Tb_Emplacement As Tb_Emplacement
    Public Overridable Property Tb_Fournisseur As Tb_Fournisseur
    Public Overridable Property Tb_Produit As Tb_Produit
    Public Overridable Property Tb_Localisation As Tb_Localisation

End Class
