'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Localisation
    Public Property InventaireID As Integer
    Public Property EmplacementID As Nullable(Of Integer)

    Public Overridable Property Tb_Emplacement As Tb_Emplacement
    Public Overridable Property Tb_Inventaire As Tb_Inventaire

End Class
