'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Membre
    Public Property ID As Integer
    Public Property NoCarte As Nullable(Of Integer)
    Public Property Nom As String
    Public Property Prenom As String
    Public Property Addresse As String
    Public Property Ville As String
    Public Property CodePostal As String
    Public Property Tel As String
    Public Property EtudiantDA As String
    Public Property EnseignantNo As String
    Public Property DateEntree As Nullable(Of Date)
    Public Property DateRemb As Nullable(Of Date)
    Public Property Don As String
    Public Property R1 As String
    Public Property R2 As String

    Public Overridable Property Tb_Facture As ICollection(Of Tb_Facture) = New HashSet(Of Tb_Facture)

End Class
