'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_NiveauAcces
    Public Property ID As Integer
    Public Property Nom As String

    Public Overridable Property Tb_Utilisateur As ICollection(Of Tb_Utilisateur) = New HashSet(Of Tb_Utilisateur)

End Class
