'------------------------------------------------------------------------------
' <auto-generated>
'    Ce code a été généré à partir d'un modèle.
'
'    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tb_Taxe
    Public Property ID As Integer
    Public Property Taxe1 As Nullable(Of Double)
    Public Property Taxe2 As Nullable(Of Double)
    Public Property DateEffective As Nullable(Of Date)

End Class
